In [2]:
import numpy as np

In [93]:
save_name='CIFAR100_BDPS_2percent_20Ps_20As_5seed_test_acc_total_seeds'

load_path = f'results/{save_name}.npy'

# npz 파일 로드
data = np.load(load_path)

print(data)
np.mean(data)

[0.9624399  0.96444311 0.96534455 0.96203926 0.96394231 0.95933494]


0.9629240117521367

In [256]:
save_name='DPS_26lines_total_10seeds'
# save_name='PADPS_26lines_70Ps_5As_total_10seeds'
# save_name='ADPS_26lines_40As_total_10seeds'

load_path = f'results_metrics_{save_name}.npz'

# npz 파일 로드
data = np.load(load_path)

# 각 배열 접근
mse_mean_list = data['mse']
PSNR_mean_list = data['psnr']
SSIM_mean_list = data['ssim']

In [257]:
# mse_mean_list[0]=mse_mean
# PSNR_mean_list[0]=PSNR_mean
# SSIM_mean_list[0]=SSIM_mean

# save_path = f'results_metrics_{save_name}.npz'
# np.savez(save_path,
#         mse=mse_mean_list,
#         psnr=PSNR_mean_list,
#         ssim=SSIM_mean_list)

In [264]:
print(np.mean(mse_mean_list))
print(np.mean(PSNR_mean_list))
print(np.mean(SSIM_mean_list)) 

0.039286017
25.450012
0.5844596


In [265]:
mse_mean_list

array([0.03818389, 0.03938958, 0.03721859, 0.04022919, 0.03889464,
       0.0407845 , 0.0377233 , 0.04147181, 0.03967868, 0.06112831],
      dtype=float32)

In [266]:
PSNR_mean_list

array([25.516472, 25.430317, 25.566046, 25.40728 , 25.591002, 25.364021,
       25.664625, 25.084055, 25.426289, 24.154774], dtype=float32)

In [267]:
SSIM_mean_list

array([0.5765987 , 0.57671934, 0.60894036, 0.58560854, 0.59860575,
       0.5827179 , 0.5974819 , 0.54610157, 0.5873624 , 0.5337086 ],
      dtype=float32)

In [268]:
0.039332375
25.441021
0.5847312

0.5847312

In [269]:
LOUPE
0.049731046
25.05975
0.57392955

NameError: name 'LOUPE' is not defined